name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import certs
        shell: bash
        env:
          DEVELOPER_ID_APPLICATION_PEM: ${{ secrets.DEVELOPER_ID_APPLICATION_PEM }}
          DEVELOPER_ID_APPLICATION_CER_B64: ${{ secrets.DEVELOPER_ID_APPLICATION_CER_B64 }}
          DEV_KEY_P12_B64: ${{ secrets.DEV_KEY_P12_B64 }}
          DEV_KEY_P12_W: ${{ secrets.DEV_KEY_P12_W }}
          CERTS_P12: ${{ secrets.CERTS_P12 }} 
        run: |
          set -eo pipefail
          #
          #####
         
          # DEV_KEY_PATH=$RUNNER_TEMP/dev_key.p12
          # DEV_ID_APP_CERT_PATH=$RUNNER_TEMP/dev_id_app.cer
          CERTS_PATH=$RUNNER_TEMP/bundle.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          KEYCHAIN_PASSWORD=foo

          # import certificate and provisioning profile from secrets
          # echo -n "$DEV_KEY_P12_B64" | base64 --decode -o $DEV_KEY_PATH
          # echo -n "$DEVELOPER_ID_APPLICATION_CER_B64" | base64 --decode -o $DEV_ID_APP_CERT_PATH
          echo -n "$CERTS_P12" | base64 -d -o "$CERTS_PATH"


          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          # echo "importing dev key"
          # security import $DEV_KEY_PATH -P "$DEV_KEY_P12_W" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          # echo "done"
          # echo "importing dev id app key"
          # security import $DEV_ID_APP_CERT_PATH -A -t cert -k $KEYCHAIN_PATH
          # echo "done"
          #
          security import "$CERTS_PATH" -P "$DEV_KEY_P12_W" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH

          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          security find-identity -vp codesigning $KEYCHAIN_PATH

          echo "meh" > foo.txt; cert_name="Developer ID Application: Stefan Matting (FPDFQ974RQ)"; codesign --force --verify --verbose=100 --sign "$cert_name" --keychain "$KEYCHAIN_PATH" foo.txt


      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'
      #
      # - shell: bash
      #   env:
      #     POINTER_CC_VERSION: ${{ env.POINTER_CC_VERSION }} 
      #   run: |
      #     python3 --version
      #     python3 -m venv venv
      #     source venv/bin/activate
      #     pip install -r requirements.txt
      #     pip install -r requirements-stage2.txt
      #     ./scripts/build.sh
      #     ./scripts/package-mac.sh
