name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import certs
        shell: bash
        env:
          DEVELOPER_ID_APPLICATION_PEM: ${{ secrets.DEVELOPER_ID_APPLICATION_PEM }}
          DEV_KEY_P12_B64: ${{ secrets.DEV_KEY_P12_B64 }}
          DEV_KEY_P12_W: ${{ secrets.DEV_KEY_P12_W }}
        run: |
          set -exo pipefail
          echo -n "$DEVELOPER_ID_APPLICATION_PEM" > /tmp/DEVELOPER_ID_APPLICATION_PEM
          echo -n "$DEV_KEY_P12_B64" | base64 -d > /tmp/DEV_KEY_P12
          pw=$(echo -n "$DEV_KEY_P12_W")
          security import /tmp/DEV_KEY_P12 -k $HOME/Library/Keychains/login.keychain -P "$pw" -A "Stefan Dev Key"
          security import "$DEVELOPER_ID_APPLICATION_PEM" -k $HOME/Library/Keychains/login.keychain
          rm -f /tmp/DEVELOPER_ID_APPLICATION_PEM
          rm -f /tmp/DEV_KEY_P12
          echo "succesfully imported"

      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'
      # - shell: bash
      #   run: |
      #     python3 --version
      #     python3 -m venv venv
      #     source venv/bin/activate
      #     pip install -r requirements.txt
      #     pip install -r requirements-stage2.txt
      #     ./scripts/build.sh
